
import React, { useState } from 'react';
import type { AnalysisResult, ChatMessage } from '../types';
import HeatmapOverlay from './HeatmapOverlay';
import ChatInterface from './ChatInterface';

interface ResultDisplayProps {
  result?: AnalysisResult;
  isLoading: boolean;
  previewUrl: string | null;
  notes?: string;
  onNotesChange: (notes: string) => void;
  chatHistory: ChatMessage[];
  isReplying: boolean;
  onSendMessage: (message: string) => void;
  isPatientView?: boolean;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ 
  result, 
  isLoading, 
  previewUrl, 
  notes, 
  onNotesChange,
  chatHistory,
  isReplying,
  onSendMessage,
  isPatientView = false,
}) => {
  const [showHeatmap, setShowHeatmap] = useState(true);

  const handleDownloadReport = () => {
    if (!result || !previewUrl) return;
    
    const isMalignant = result.diagnosis === 'Malignant';
    const statusColor = isMalignant ? '#e11d48' : '#10b981';
    
    const reportHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Diagnostic Report - XAI Platform</title>
  <style>
    body { font-family: 'Inter', -apple-system, sans-serif; color: #1e293b; line-height: 1.6; padding: 40px; max-width: 800px; margin: auto; }
    .header { border-bottom: 2px solid #f1f5f9; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
    .logo { font-weight: 800; font-size: 24px; color: #0f172a; }
    .date { font-size: 12px; color: #64748b; font-weight: 600; text-transform: uppercase; }
    .badge { display: inline-block; padding: 8px 16px; border-radius: 12px; font-weight: 800; text-transform: uppercase; font-size: 14px; margin-bottom: 10px; }
    .diagnosis-malignant { background: #fff1f2; color: #e11d48; border: 1px solid #ffe4e6; }
    .diagnosis-benign { background: #ecfdf5; color: #10b981; border: 1px solid #d1fae5; }
    .section { margin-bottom: 40px; }
    .section-title { font-size: 10px; font-weight: 900; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 15px; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px; }
    .image-container { background: #000; border-radius: 20px; overflow: hidden; margin-top: 10px; text-align: center; border: 4px solid #f8fafc; }
    .clinical-image { max-width: 100%; max-height: 400px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .feature-card { background: #f8fafc; padding: 15px; border-radius: 12px; border: 1px solid #f1f5f9; }
    .feature-num { font-weight: 900; color: ${statusColor}; margin-right: 8px; }
    .notes-box { background: #fdfdfd; border: 1px dashed #e2e8f0; padding: 20px; border-radius: 16px; font-style: italic; color: #334155; }
    footer { margin-top: 60px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #f1f5f9; pt: 20px; }
    @media print { body { padding: 0; } .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">XAI Platform <span style="color: #e11d48;">Diagnostic</span></div>
    <div class="date">Report ID: ${Date.now()} | Generated: ${new Date().toLocaleDateString()}</div>
  </div>

  <div class="section">
    <div class="badge ${isMalignant ? 'diagnosis-malignant' : 'diagnosis-benign'}">
      AI Diagnostic Result: ${result.diagnosis}
    </div>
    <div style="font-size: 32px; font-weight: 900; color: ${statusColor}; letter-spacing: -0.02em;">
      Confidence Level: ${(result.confidence * 100).toFixed(2)}%
    </div>
  </div>

  <div class="section">
    <div class="section-title">Clinical Imaging Evidence</div>
    <div class="image-container">
      <img src="${previewUrl}" class="clinical-image" alt="Clinical Scan">
    </div>
  </div>

  <div class="grid">
    <div class="section">
      <div class="section-title">Local Interpretability (LIME)</div>
      <p style="font-weight: 500; font-size: 14px; color: #475569;">${result.limeExplanation}</p>
    </div>
    <div class="section">
      <div class="section-title">Contributing Features (SHAP)</div>
      <div style="font-size: 13px; font-weight: 600;">
        ${result.shapExplanation.map((f, i) => `
          <div style="margin-bottom: 8px;">
            <span class="feature-num">${i + 1}</span> ${f}
          </div>
        `).join('')}
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Clinician Observations & Notes</div>
    <div class="notes-box">
      ${notes || 'No clinician observations recorded for this study.'}
    </div>
  </div>

  <footer>
    This document is a clinical decision support output generated by the DenseNet-XAI Model v2.1.<br>
    Built by Digital Storm Oncology • Visvesvaraya Technological University
  </footer>

  <div class="no-print" style="position: fixed; bottom: 20px; right: 20px;">
    <button onclick="window.print()" style="background: #0f172a; color: white; border: none; padding: 12px 24px; border-radius: 12px; font-weight: 700; cursor: pointer; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);">
      Print / Save as PDF
    </button>
  </div>
</body>
</html>
    `;

    const blob = new Blob([reportHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Diagnostic_Report_Case_${result.diagnosis}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="text-center py-20 flex flex-col items-center justify-center min-h-[300px]">
        <div className="animate-spin rounded-full h-10 w-10 lg:h-12 lg:w-12 border-b-2 border-rose-600"></div>
        <p className="text-slate-600 dark:text-slate-400 mt-4 font-medium text-sm lg:text-base">AI is analyzing the medical imagery...</p>
        <p className="text-xs text-slate-500 mt-1">Extracting XAI saliency features...</p>
      </div>
    );
  }

  if (!result) {
    return (
        <div className="space-y-6">
            <div>
              <h3 className="text-xs lg:text-sm font-bold uppercase tracking-widest text-slate-400 mb-3">Medical Image Source</h3>
              <div className="relative w-full aspect-square rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-800 bg-black shadow-inner">
                {previewUrl ? 
                  <img src={previewUrl} alt="Pending analysis" className="w-full h-full object-contain" /> :
                  <div className="flex items-center justify-center h-full text-slate-500 text-xs">Waiting for upload...</div>
                }
              </div>
            </div>
            <div className="text-center py-8 lg:py-12 text-slate-500 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-dashed border-slate-200 dark:border-slate-800">
                <p className="text-sm font-semibold">{isPatientView ? 'Your report is not yet available.' : 'Pending specialized AI inference.'}</p>
                {!isPatientView && <p className="text-xs mt-2 opacity-60">Complete study registration and click "Run AI Diagnostic".</p>}
            </div>
             <div className="mt-4 pt-4 border-t dark:border-slate-800">
                 <ChatInterface 
                    history={[]}
                    isReplying={false}
                    onSendMessage={() => {}}
                    disabled={true}
                 />
            </div>
        </div>
    );
  }

  if (result.diagnosis === 'Invalid') {
    return (
      <div className="space-y-6 animate-in fade-in duration-300 max-w-xl mx-auto py-10">
        <div className="p-8 bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-900/30 rounded-3xl text-center space-y-4">
            <div className="w-16 h-16 bg-amber-100 dark:bg-amber-900/40 rounded-full flex items-center justify-center mx-auto mb-2 text-3xl">⚠️</div>
            <h3 className="text-xl font-black text-amber-800 dark:text-amber-400">Non-Medical Image</h3>
            <p className="text-sm text-amber-700 dark:text-amber-500/80 leading-relaxed font-medium">
              {result.limeExplanation || "The system determined this upload is not a valid clinical breast scan. Please provide high-resolution mammography or ultrasound imagery for diagnostic support."}
            </p>
        </div>
        <div className="mt-4 pt-4 border-t dark:border-slate-800">
           <ChatInterface 
              history={chatHistory}
              isReplying={isReplying}
              onSendMessage={onSendMessage}
           />
        </div>
      </div>
    );
  }

  const isMalignant = result.diagnosis === 'Malignant';
  const confidencePercentage = (result.confidence * 100).toFixed(1);

  return (
    <div className="flex flex-col h-full animate-in slide-in-from-bottom-2 duration-500 pb-10">
      <div className="space-y-6 lg:space-y-10">
        <div className={`p-5 lg:p-8 rounded-3xl border ${isMalignant ? 'bg-rose-50 dark:bg-rose-900/20 border-rose-100 dark:border-rose-900/30 shadow-sm shadow-rose-100 dark:shadow-none' : 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-100 dark:border-emerald-900/30 shadow-sm shadow-emerald-100 dark:shadow-none'}`}>
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4 text-center sm:text-left">
            <div className="space-y-1">
              <span className="text-[10px] font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400 block">AI Diagnostic Yield</span>
              <span className={`text-3xl lg:text-4xl font-black tracking-tighter ${isMalignant ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
                {result.diagnosis.toUpperCase()}
              </span>
            </div>
            {!isPatientView && (
              <div className="sm:text-right flex flex-col items-center sm:items-end gap-3">
                <div className="flex flex-col items-center sm:items-end">
                    <p className={`text-[10px] font-black tracking-[0.2em] ${isMalignant ? 'text-rose-700 dark:text-rose-50' : 'text-emerald-700 dark:text-emerald-50'}`}>CONFIDENCE SCORE</p>
                    <p className={`text-3xl lg:text-4xl font-black ${isMalignant ? 'text-rose-800 dark:text-rose-300' : 'text-emerald-800 dark:text-emerald-300'}`}>{confidencePercentage}%</p>
                </div>
                <button 
                  onClick={handleDownloadReport}
                  className="bg-slate-900 dark:bg-slate-800 text-white px-4 py-2 rounded-xl text-xs font-bold hover:bg-slate-800 transition-all flex items-center space-x-2"
                >
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5l5 5v11a2 2 0 01-2 2z" /></svg>
                  <span>Export Imaging Report</span>
                </button>
              </div>
            )}
            {isPatientView && (
                <button 
                onClick={handleDownloadReport}
                className="bg-rose-600 text-white px-6 py-3 rounded-2xl text-sm font-bold hover:bg-rose-700 transition-all flex items-center space-x-2 shadow-lg"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5l5 5v11a2 2 0 01-2 2z" /></svg>
                <span>Download My Visual Report</span>
              </button>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-8">
            <div className="rounded-3xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm bg-white dark:bg-slate-900">
                <div className="px-5 py-3 border-b dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50">
                    <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400">Clinical Input</h4>
                </div>
                <div className="relative aspect-square bg-black">
                    {previewUrl && <img src={previewUrl} alt="Original" className="w-full h-full object-contain" />}
                </div>
            </div>

            <div className="rounded-3xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm bg-white dark:bg-slate-900">
                <div className="px-5 py-3 border-b dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50 flex justify-between items-center">
                    <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400">XAI Saliency Map</h4>
                     {!isPatientView && (
                        <button 
                          onClick={() => setShowHeatmap(!showHeatmap)}
                          className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase transition-all ${showHeatmap ? 'bg-rose-100 text-rose-700 dark:bg-rose-900/30' : 'bg-slate-100 text-slate-600 dark:bg-slate-800'}`}
                        >
                          {showHeatmap ? 'Layer On' : 'Layer Off'}
                        </button>
                    )}
                </div>
                <div className="relative aspect-square bg-black">
                    {previewUrl && <img src={previewUrl} alt="Analysis" className="w-full h-full object-contain opacity-80" />}
                    {showHeatmap && <HeatmapOverlay region={result.gradCamRegion} />}
                </div>
            </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-8">
          <div className="lg:col-span-2 space-y-6 lg:space-y-8">
            <div className="bg-slate-50 dark:bg-slate-900/50 p-6 lg:p-8 rounded-[2rem] border border-slate-100 dark:border-slate-800 shadow-inner">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-4">Local Visual Evidence (LIME)</h3>
              <p className="text-slate-700 dark:text-slate-300 text-base leading-relaxed font-medium italic">"{result.limeExplanation}"</p>
            </div>
            
            {!isPatientView && (
                <div className="bg-white dark:bg-slate-900 p-6 lg:p-8 rounded-[2rem] border border-slate-200 dark:border-slate-800">
                  <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-6">Top Contributing Features (SHAP)</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    {result.shapExplanation.map((feature, index) => (
                      <div key={index} className="flex flex-col items-center text-center bg-slate-50 dark:bg-slate-800 p-5 rounded-2xl border border-slate-100 dark:border-slate-700/50">
                        <span className={`w-8 h-8 flex items-center justify-center font-black text-white text-xs rounded-xl mb-3 shadow-lg ${isMalignant ? 'bg-rose-500 shadow-rose-200 dark:shadow-none' : 'bg-emerald-500 shadow-emerald-200 dark:shadow-none'}`}>
                          {index + 1}
                        </span>
                        <span className="text-sm font-bold text-slate-700 dark:text-slate-200 tracking-tight">{feature}</span>
                      </div>
                    ))}
                  </div>
                </div>
            )}
          </div>

          <div className="bg-white dark:bg-slate-900 p-6 lg:p-8 rounded-[2rem] border border-slate-200 dark:border-slate-800 flex flex-col">
            <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-4">Clinician Observations</h3>
            {isPatientView ? (
               <div className="flex-grow p-4 bg-slate-50 dark:bg-slate-800/50 rounded-2xl border border-slate-100 dark:border-slate-800/50">
                  <p className="text-sm text-slate-700 dark:text-slate-300 font-medium">{notes || 'Final report pending radiologist signature.'}</p>
               </div>
            ) : (
              <textarea
                value={notes}
                onChange={(e) => onNotesChange(e.target.value)}
                placeholder="Document morphological traits, BIRADS categorization, and recommended follow-up..."
                className="flex-grow w-full min-h-[200px] p-5 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-rose-500 transition dark:text-white text-sm outline-none shadow-inner resize-none font-medium"
              ></textarea>
            )}
          </div>
        </div>
      </div>
      
      <div className="mt-12 pt-12 border-t dark:border-slate-800">
         <ChatInterface 
            history={chatHistory}
            isReplying={isReplying}
            onSendMessage={onSendMessage}
            disabled={isPatientView}
         />
      </div>
    </div>
  );
};

export default ResultDisplay;
